# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='author.Author', verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
