# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verse', '0002_auto_20160918_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='verses_liked', to=settings.AUTH_USER_MODEL, verbose_name='Понравилось пользователям'),
        ),
    ]
